Lab5_ASP.NET/Models/ExtendedEventModel.cs
using BLL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PL.Models
{
    public class ExtendedEventModel : EventModel
    {
        public List<ManagerModel> Managers { get; set; }
        public ExtendedEventModel() { }
        public ExtendedEventModel(List<ManagerModel> Managers)
        {
            this.Managers = Managers;
        }
        public ExtendedEventModel(EventModel @event, List<ManagerModel> Managers)
        {
            this.id = @event.id;
            this.name = @event.name;
            this.description = @event.description;
            this.date = @event.date;
            this.authorID = @event.authorID;
            this.Managers = Managers;
        }
    }
}

Lab5_ASP.NET/Models/ExtendedReportModel.cs
using BLL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PL.Models
{
    public class ExtendedReportModel
    {
        public List<ManagerReport> ReportData { get; set; }
        public List<OrganizationModel> Organizations { get; set; }
        public Guid OrganizationID { get; set; }
    }
}

Lab5_ASP.NET/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.Interfaces;
using BLL.Models;
using PL.Models;  

namespace PL.Controllers
{
    public class EventsController : Controller
    {
        // GET: Events
        IDataBaseCRUD dataBaseCRUD;
        
        public EventsController(IDataBaseCRUD dataBaseCRUD)
        {
            this.dataBaseCRUD = dataBaseCRUD;
        }
        public ActionResult Index()
        {
            return View("Index", dataBaseCRUD.GetAllEvents());
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View(new ExtendedEventModel(dataBaseCRUD.GetAllManagers()));
        }
        [HttpPost]
        public ActionResult Create(ExtendedEventModel @event)
        {
            EventModel newEvent = new EventModel();
            newEvent.name = @event.name;
            newEvent.date = @event.date;
            newEvent.description = @event.description;
            newEvent.authorID = @event.authorID;

            dataBaseCRUD.CreateEvent(newEvent);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Update(Guid id)
        {
            ExtendedEventModel @event = new ExtendedEventModel(dataBaseCRUD.GetEvent(id), dataBaseCRUD.GetAllManagers());

            return View(@event);
        }
        [HttpPost]
        public ActionResult Update(ExtendedEventModel @event)
        {
            EventModel newEvent = new EventModel();
            newEvent.id = @event.id;
            newEvent.name = @event.name;
            newEvent.description = @event.description;
            newEvent.date = @event.date;
            newEvent.authorID = @event.authorID;

            dataBaseCRUD.UpdateEvent(newEvent);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            dataBaseCRUD.DeleteEvent(id);

            return RedirectToAction("Index");
        }
    }
}

Lab5_ASP.NET/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lab5_ASP.NET/Controllers/ManagersController.cs
using BLL.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class ManagersController : Controller
    {
        // GET: Managers
        IDataBaseCRUD dataBaseCRUD;
        public ManagersController(IDataBaseCRUD dataBaseCRUD)
        {
            this.dataBaseCRUD = dataBaseCRUD;
        }
        public ActionResult Index()
        {
            return View("Index", dataBaseCRUD.GetAllManagers());
        }
    }
}

Lab5_ASP.NET/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.Interfaces;
using PL.Models;

namespace PL.Controllers
{
    public class ReportController : Controller
    {
        // GET: Report
        IDataBaseCRUD dataBaseCRUD;
        IReportService reportService;
        public ReportController(IDataBaseCRUD dataBaseCRUD, IReportService reportService)
        {
            this.dataBaseCRUD = dataBaseCRUD;
            this.reportService = reportService;
        }
        [HttpGet]
        public ActionResult Index()
        {
            return View(new ExtendedReportModel() { Organizations = dataBaseCRUD.GetAllOrganizations() });
        }
        [HttpPost]
        public ActionResult Index(ExtendedReportModel report)
        {
            report.ReportData = reportService.ManagersOfOrganization(report.OrganizationID);
            report.Organizations = dataBaseCRUD.GetAllOrganizations();

            return View(report);
        }

    }
}

Lab5_ASP.NET/Views/Events/Create.cshtml
@model PL.Models.ExtendedEventModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>ExtendedEventModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.authorID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.authorID, new SelectList(Model.Managers, "userID", "name"), new { })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Lab5_ASP.NET/Views/Events/Delete.cshtml
@model BLL.Models.EventModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>EventModel</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.description)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.authorID)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.authorID)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.date)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.date)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Lab5_ASP.NET/Views/Events/Index.cshtml
@model IEnumerable<BLL.Models.EventModel>

@{
    ViewBag.Title = "Список событий";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.authorID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.date)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.authorID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
            <td>
                @Html.ActionLink("Изменить", "Update", new { id=item.id }) |
                @Html.ActionLink("Удалить", "Delete", new { id=item.id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

Lab5_ASP.NET/Views/Events/Update.cshtml
@model PL.Models.ExtendedEventModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Update</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>ExtendedEventModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.authorID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.authorID, new SelectList(Model.Managers, "userID", "name"), new { })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Lab5_ASP.NET/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Lab5_ASP.NET/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Lab5_ASP.NET/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Домашняя страница";
}

<div>
    <h1>Данное приложение демонстрирует работу с ASP.NET и паттерном MVC.</h1>
</div>

Lab5_ASP.NET/Views/Managers/Index.cshtml
@model IEnumerable<BLL.Models.ManagerModel>

@{
    ViewBag.Title = "Список менеджеров";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Создать событие", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.organization)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nickname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.email)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.organization)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nickname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

Lab5_ASP.NET/Views/Report/Index.cshtml
@model PL.Models.ExtendedReportModel

@{
    ViewBag.Title = "Менеджеры организации";
}

<div class="row">
    <h1>Менеджеры организации</h1>
    @using (Html.BeginForm())
    {
        @Html.DropDownListFor(model => model.OrganizationID, new SelectList(Model.Organizations, "id", "name"), new { })
        <input type="submit" value="Найти" class="btn btn-default" />
    }
</div>

<div class="row">
    <table class="table">
        <tr>
            <th>
                Имя
            </th>
            <th>
                Логин
            </th>
            <th>
                Почта
            </th>
            <th>
                Организация
            </th>
        </tr>

        @if (Model.ReportData != null)
        {
            foreach (var item in Model.ReportData)
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ManagerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nickname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Organization)
            </td>
        </tr>
            }
        }
    </table>
</div>

Lab5_ASP.NET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Лабораторная работа #5</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top header">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("События", "Index", "Events")</li>
                    <li>@Html.ActionLink("Менеджеры", "Index", "Managers")</li>
                    <li>@Html.ActionLink("Отчет", "Index", "Report")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="footer-text">&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>